### ISSUE TITLE
fix examples/indexing.py

### ISSUE THREAD

**Issue by github-4o** [personal-army-of-4o/nyanMigen#95]
https://github.com/personal-army-of-4o/nyanMigen/blob/c4122d192fbbf65e2d4bce3f2327629b8c39331c/examples/indexing.nmigen
`python3 examples/indexing.nmigen generate -t v` produces error:
```
Traceback (most recent call last):
  File "examples/indexing.nmigen", line 43, in <module>
    indexing.main()
  File "examples/indexing.nmigen", line 9, in main
    main(top, name='indexing', ports=top.ports())
  File "/home/pi/repos/nmigen/nmigen/cli.py", line 82, in main
    main_runner(parser, parser.parse_args(), *args, **kwargs)
  File "/home/pi/repos/nmigen/nmigen/cli.py", line 50, in main_runner
    fragment = Fragment.get(design, platform)
  File "/home/pi/repos/nmigen/nmigen/hdl/ir.py", line 39, in get
    obj = obj.elaborate(platform)
  File "examples/indexing.nmigen", line 34, in elaborate
    m.d.comb += ari[i][j][k].eq(inp[(((i * (n ** 2)) + (j * n)) + k)])
TypeError: 'ABCMeta' object is not subscriptable
```

**Comment by github-4o** [comment]
code error
